name: Run tests

on: [ pull_request ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
      - name: Test
        run: mvn clean install -DskipTests=false --update-snapshots -q

  artifact:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Release Maven package
        env:
          SONATYPE_PORTAL_USERNAME: ${{ secrets.SONATYPE_PORTAL_USERNAME }}
          SONATYPE_PORTAL_PASSWORD: ${{ secrets.SONATYPE_PORTAL_PASSWORD }}
        run: |
          mvn clean deploy --settings .mvn/settings.xml -Dmaven.test.skip=true -B
