name: Merge to Master

on:
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Test
      run: mvn clean install -DskipTests=false --update-snapshots -q

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04
    needs: unit-test

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
